#Configurar ruta de datasets
train:
  - /home/surones/TeamAware/NewDataset/AnnotatedFlood/images/train/
  - /home/surones/TeamAware/NewDataset/fire/images/train/
  - /home/surones/TeamAware/NewDataset/FORESTFIRE/images/train/
  - /home/surones/TeamAware/NewDataset/TRAINS/images/train/
  - /home/surones/TeamAware/NewDataset/smoke/images/train/
  - /home/surones/TeamAware/NewDataset/coco_reducido/images/train/
  - /home/surones/TeamAware/NewDataset/BomberoFuego/images/train/
  - /home/surones/TeamAware/NewDataset/bomberofuego1/images/train/
  - /home/surones/TeamAware/NewDataset/bomberolargos/images/train/


val:
  - /home/surones/TeamAware/NewDataset/AnnotatedFlood/images/valid/
  - /home/surones/TeamAware/NewDataset/fire/images/valid/
  - /home/surones/TeamAware/NewDataset/FORESTFIRE/images/valid/
  - /home/surones/TeamAware/NewDataset/TRAINS/images/valid/
  - /home/surones/TeamAware/NewDataset/smoke/images/valid/
  - /home/surones/TeamAware/NewDataset/coco_reducido/images/valid/
  - /home/surones/TeamAware/NewDataset/BomberoFuego/images/valid/
  - /home/surones/TeamAware/NewDataset/bomberofuego1/images/valid/
  - /home/surones/TeamAware/NewDataset/bomberolargos/images/valid/


train_labels:
  - /home/surones/TeamAware/NewDataset/AnnotatedFlood/labels/train/
  - /home/surones/TeamAware/NewDataset/fire/labels/train/
  - /home/surones/TeamAware/NewDataset/FORESTFIRE/labels/train/
  - /home/surones/TeamAware/NewDataset/TRAINS/labels/train/
  - /home/surones/TeamAware/NewDataset/smoke/labels/train/
  - /home/surones/TeamAware/NewDataset/coco_reducido/labels/train/
  - /home/surones/TeamAware/NewDataset/BomberoFuego/labels/train/
  - /home/surones/TeamAware/NewDataset/bomberofuego1/labels/train/
  - /home/surones/TeamAware/NewDataset/bomberolargos/labels/train/

valid_labels:
  - /home/surones/TeamAware/NewDataset/AnnotatedFlood/labels/valid/
  - /home/surones/TeamAware/NewDataset/fire/labels/valid/
  - /home/surones/TeamAware/NewDataset/FORESTFIRE/labels/valid/
  - /home/surones/TeamAware/NewDataset/TRAINS/labels/valid/
  - /home/surones/TeamAware/NewDataset/smoke/labels/valid/
  - /home/surones/TeamAware/NewDataset/coco_reducido/labels/valid/
  - /home/surones/TeamAware/NewDataset/BomberoFuego/labels/valid/
  - /home/surones/TeamAware/NewDataset/bomberofuego1/labels/valid/
  - /home/surones/TeamAware/NewDataset/bomberolargos/labels/valid/



# Classes
names:
  0: person
  1: bicycle
  2: car
  3: motorbike
  4: bus
  5: train
  6: truck
  7: animal
  8: backpack
  9: fire
  10: smoke
  11: flood
  12: doors
  13: stairs
  14: windows
  15: suitcase
  16: cellphone
